# Final Capstone Project

This notebook is going to be the final notebook for the capstone project.

## Importing appropriate packages

In [1]:
# standard packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb

# packages for clustering
from sklearn.cluster import KMeans
from sklearn.cluster import AgglomerativeClustering
import scipy.cluster.hierarchy as hc
from sklearn.metrics import silhouette_score
from sklearn.manifold import TSNE

# preprocessing packages
from sklearn.preprocessing import MinMaxScaler
from scipy.cluster.hierarchy import dendrogram, linkage
from sklearn.decomposition import PCA

import json # library to handle JSON files

from geopy.geocoders import Nominatim # convert an address into latitude and longitude values
import geocoder # to get coordinates

import requests # library to handle requests
from bs4 import BeautifulSoup # library to parse HTML and XML documents

from pandas.io.json import json_normalize # tranform JSON file into a pandas dataframe

import folium # map rendering library

print('All packages are imported.')

All packages are imported.

## Webscrape a webpage for each of the zipcodes of New York City

In [2]:
# send the GET request
data = requests.get("https://en.wikipedia.org/wiki/Category:Neighborhoods_in_the_Bronx").text

# parse data from the html into a beautifulsoup object
soup = BeautifulSoup(data, 'html.parser')

# create a list to store neighborhood data
neighborhoodList = []

# append the data into the list
for row in soup.find_all("div", class_="mw-category")[0].findAll("li"):
    neighborhoodList.append(row.text)

# create a new DataFrame from the list
bx = pd.DataFrame({"Neighborhood": neighborhoodList})


bx['Neighborhood'] = bx['Neighborhood'].astype(str).str[1:]


sep = '('
bx['Neighborhood'] = bx['Neighborhood'].apply(lambda x: x.split(sep,1)[0])
bx['Neighborhood'] = bx['Neighborhood'].str.strip()

In [4]:
# define a function to get coordinates
def get_latlng(neighborhood):
    # initialize your variable to None
    lat_lng_coords = None
    # loop until you get the coordinates
    while(lat_lng_coords is None):
        g = geocoder.arcgis('{}, Bronx, New York'.format(neighborhood))
        lat_lng_coords = g.latlng
    return lat_lng_coords

# call the function to get the coordinates, store in a new list using list comprehension
coords = [ get_latlng(neighborhood) for neighborhood in bx["Neighborhood"].tolist() ]

In [5]:
# create temporary dataframe to populate the coordinates into Latitude and Longitude
df_coords = pd.DataFrame(coords, columns=['Latitude', 'Longitude'])

# merge the coordinates into the original dataframe
bx['Latitude'] = df_coords['Latitude']
bx['Longitude'] = df_coords['Longitude']

In [6]:
# save the DataFrame as CSV file
bx.to_csv("bx_neighborhoods.csv", index=False)

# check the neighborhoods and the coordinates
print(bx.shape)
bx

(31, 3)

                   Neighborhood   Latitude  Longitude
0          Bedford Park, Bronx‎  40.869990  -73.88573
1               Belmont, Bronx‎  40.855460  -73.88569
2           City Island, Bronx‎  40.855640  -73.79171
3            Co-op City, Bronx‎  40.879939  -73.82317
4             Concourse, Bronx‎  40.827630  -73.92533
5           Eastchester, Bronx‎  40.888110  -73.82835
6               Fordham, Bronx‎  40.858940  -73.89885
7            Highbridge, Bronx‎  40.842117  -73.92820
8           Hunts Point, Bronx‎  40.812420  -73.88450
9           Jerome Park, Bronx‎  40.865470  -73.89896
10  Kingsbridge Heights, Bronx‎  40.870030  -73.89821
11          Kingsbridge, Bronx‎  40.883700  -73.90273
12             Longwood, Bronx‎  40.817480  -73.89816
13              Melrose, Bronx‎  40.824430  -73.91070
14       Morris Heights, Bronx‎  40.849710  -73.91985
15          Morris Park, Bronx‎  40.848300  -73.85513
16           Morrisania, Bronx‎  40.828860  -73.90680
17           Mott Haven, Bronx‎  40.808990  -73.92295
18              Norwood, Bronx‎  40.878690  -73.87929
19          Parkchester, Bronx‎  40.839130  -73.86109
20          Port Morris, Bronx‎  40.801340  -73.90996
21            Riverdale, Bronx‎  40.900190  -73.90697
22            Soundview, Bronx‎  40.822910  -73.86827
23       Spuyten Duyvil, Bronx‎  40.881180  -73.91773
24         Throggs Neck, Bronx‎  40.821138  -73.81281
25              Tremont, Bronx‎  40.849390  -73.90627
26   University Heights, Bronx‎  40.860190  -73.90971
27             Van Nest, Bronx‎  40.849030  -73.86463
28           West Farms, Bronx‎  40.839760  -73.87793
29   Westchester Square, Bronx‎  40.841120  -73.84281
30       Williamsbridge, Bronx‎  40.877250  -73.85660

## Manhattan

In [7]:
# send the GET request
data = requests.get("https://en.wikipedia.org/wiki/Category:Neighborhoods_in_Manhattan").text

# parse data from the html into a beautifulsoup object
soup = BeautifulSoup(data, 'html.parser')

# create a list to store neighborhood data
neighborhoodList = []

# append the data into the list
for row in soup.find_all("div", class_="mw-category")[0].findAll("li"):
    neighborhoodList.append(row.text)

# create a new DataFrame from the list
mh = pd.DataFrame({"Neighborhood": neighborhoodList})


mh['Neighborhood'] = mh['Neighborhood'].astype(str).str[1:]


sep = '('
mh['Neighborhood'] = mh['Neighborhood'].apply(lambda x: x.split(sep,1)[0])
mh['Neighborhood'] = mh['Neighborhood'].str.strip()

In [8]:
# define a function to get coordinates
def get_latlng(neighborhood):
    # initialize your variable to None
    lat_lng_coords = None
    # loop until you get the coordinates
    while(lat_lng_coords is None):
        g = geocoder.arcgis('{}, Manhattan, New York'.format(neighborhood))
        lat_lng_coords = g.latlng
    return lat_lng_coords

# call the function to get the coordinates, store in a new list using list comprehension
coords = [ get_latlng(neighborhood) for neighborhood in mh["Neighborhood"].tolist() ]

In [9]:
# create temporary dataframe to populate the coordinates into Latitude and Longitude
df_coords = pd.DataFrame(coords, columns=['Latitude', 'Longitude'])

# merge the coordinates into the original dataframe
mh['Latitude'] = df_coords['Latitude']
mh['Longitude'] = df_coords['Longitude']

# save the DataFrame as CSV file
mh.to_csv("mh_neighborhoods.csv", index=False)

# check the neighborhoods and the coordinates
print(mh.shape)
mh

(44, 3)

                        Neighborhood   Latitude   Longitude
0                 Battery Park City‎  40.711310  -74.015900
1                            Bowery‎  40.723280  -73.992893
2                Chelsea, Manhattan‎  40.746100  -74.000450
3           Civic Center, Manhattan‎  40.713370  -74.003800
4                   Columbus Circle‎  40.765730  -73.983380
5                       East Harlem‎  40.798280  -73.940810
6           East Village, Manhattan‎  40.728040  -73.984990
7     Financial District, Manhattan‎  40.708260  -74.014100
8            Five Points, Manhattan‎  45.858578 -111.328778
9                 Flatiron District‎  40.739420  -73.990350
10                 Governors Island‎  40.691850  -74.013360
11                    Gramercy Park‎  40.738212  -73.985662
12                Greenwich Village‎  40.728560  -74.004890
13      Hamilton Heights, Manhattan‎  40.822380  -73.949680
14                           Harlem‎  40.808810  -73.947960
15        Hell's Kitchen, Manhattan‎  40.758110  -74.000280
16                    Hudson Square‎  43.153556  -77.601247
17          Hudson Yards, Manhattan‎  40.753416  -74.000022
18                Inwood, Manhattan‎  40.714500  -74.006010
19              Kips Bay, Manhattan‎  40.714500  -74.006010
20        Lincoln Square, Manhattan‎  40.773212  -73.981866
21                     Little Spain‎  40.714500  -74.006010
22                  Lower East Side‎  40.719130  -73.987630
23                  Lower Manhattan‎  40.719130  -73.987630
24  Meatpacking District, Manhattan‎  40.740660  -74.006820
25                Midtown Manhattan‎  40.760310  -74.002850
26   Morningside Heights, Manhattan‎  40.810530  -73.962060
27           Murray Hill, Manhattan‎  40.748550  -73.976050
28                           Nolita‎  40.723200  -73.995310
29               Pennsylvania Plaza‎  40.749922  -73.992758
30                 Roosevelt Island‎  40.764560  -73.947320
31             Rose Hill, Manhattan‎  40.714500  -74.006010
32                  SoHo, Manhattan‎  40.710369  -73.992219
33           South Ferry, Manhattan‎  40.701142  -74.013903
34      Theater District, Manhattan‎  40.758880  -73.984820
35                          Tribeca‎  40.718540  -74.008880
36          Union Square, Manhattan‎  40.736870  -73.989960
37                  Upper East Side‎  40.770620  -73.957030
38                  Upper Manhattan‎  40.820520  -73.943830
39                  Upper West Side‎  40.792510  -73.973200
40    Washington Heights, Manhattan‎  40.849830  -73.936030
41                     West Village‎  40.734970  -74.004830
42               World Trade Center‎  40.712569  -74.014081
43             Yorkville, Manhattan‎  40.778080  -73.948500

## Brooklyn

In [10]:
# send the GET request
data = requests.get("https://en.wikipedia.org/wiki/Category:Neighborhoods_in_Brooklyn").text

# parse data from the html into a beautifulsoup object
soup = BeautifulSoup(data, 'html.parser')

# create a list to store neighborhood data
neighborhoodList = []

# append the data into the list
for row in soup.find_all("div", class_="mw-category")[0].findAll("li"):
    neighborhoodList.append(row.text)

# create a new DataFrame from the list
bk = pd.DataFrame({"Neighborhood": neighborhoodList})


bk['Neighborhood'] = bk['Neighborhood'].astype(str).str[1:]


sep = '('
bk['Neighborhood'] = bk['Neighborhood'].apply(lambda x: x.split(sep,1)[0])
bk['Neighborhood'] = bk['Neighborhood'].str.strip()

In [11]:
# define a function to get coordinates
def get_latlng(neighborhood):
    # initialize your variable to None
    lat_lng_coords = None
    # loop until you get the coordinates
    while(lat_lng_coords is None):
        g = geocoder.arcgis('{}, Brooklyn, New York'.format(neighborhood))
        lat_lng_coords = g.latlng
    return lat_lng_coords

# call the function to get the coordinates, store in a new list using list comprehension
coords = [ get_latlng(neighborhood) for neighborhood in bk["Neighborhood"].tolist() ]

# create temporary dataframe to populate the coordinates into Latitude and Longitude
df_coords = pd.DataFrame(coords, columns=['Latitude', 'Longitude'])

# merge the coordinates into the original dataframe
bk['Latitude'] = df_coords['Latitude']
bk['Longitude'] = df_coords['Longitude']

In [12]:
# save the DataFrame as CSV file
bk.to_csv("bk_neighborhoods.csv", index=False)


# check the neighborhoods and the coordinates
print(bk.shape)
bk

(40, 3)

                             Neighborhood   Latitude  Longitude
0                    Bay Ridge, Brooklyn‎  40.619600 -74.027569
1           Bedford–Stuyvesant, Brooklyn‎  40.681945 -73.933294
2                  Bensonhurst, Brooklyn‎  40.604820 -73.995280
3                            Boerum Hill‎  40.689430 -73.988010
4                 Borough Park, Brooklyn‎  40.638820 -73.989120
5                         Brighton Beach‎  40.574570 -73.953430
6                       Brooklyn Heights‎  40.695350 -73.994050
7                     Brooklyn Navy Yard‎  40.705177 -73.971624
8                  Brownsville, Brooklyn‎  40.671134 -73.913476
9                     Bushwick, Brooklyn‎  40.713488 -73.941454
10                    Canarsie, Brooklyn‎  40.632325 -73.892372
11             Carroll Gardens, Brooklyn‎  40.686610 -73.967540
12                Clinton Hill, Brooklyn‎  40.698656 -73.969738
13                 Cobble Hill, Brooklyn‎  40.686730 -73.992101
14                          Coney Island‎  40.575500 -73.978450
15               Crown Heights, Brooklyn‎  40.665100 -73.948154
16               Cypress Hills, Brooklyn‎  40.690364 -73.877394
17                     Downtown Brooklyn‎  40.693630 -73.982880
18               Dyker Heights, Brooklyn‎  40.618881 -74.008897
19               East Flatbush, Brooklyn‎  40.635995 -73.945082
20               East New York, Brooklyn‎  40.666470 -73.967231
21                    Flatbush, Brooklyn‎  40.670758 -73.967745
22                   Flatlands, Brooklyn‎  40.642624 -73.902259
23                 Fort Greene, Brooklyn‎  40.686577 -73.976450
24                     Gowanus, Brooklyn‎  40.651042 -74.010956
25                   Gravesend, Brooklyn‎  40.586280 -73.998051
26                  Greenpoint, Brooklyn‎  40.730603 -73.950032
27             Manhattan Beach, Brooklyn‎  40.577820 -73.943550
28                 Marine Park, Brooklyn‎  40.604130 -73.931150
29                     Midwood, Brooklyn‎  40.660050 -73.951579
30                  Mill Basin, Brooklyn‎  40.613660 -73.906626
31                            Park Slope‎  40.670440 -73.987180
32  People from Brooklyn by neighborhood‎  40.678785 -73.944084
33            Prospect Heights, Brooklyn‎  40.700683 -73.987865
34                    Red Hook, Brooklyn‎  40.691373 -73.988700
35                    Sea Gate, Brooklyn‎  40.577602 -74.005746
36              Sheepshead Bay, Brooklyn‎  40.583580 -73.942480
37                        South Brooklyn‎  40.683880 -73.995710
38                 Sunset Park, Brooklyn‎  40.648410 -74.006660
39                Williamsburg, Brooklyn‎  40.700051 -73.962456

## Queens

In [14]:
# send the GET request
data = requests.get("https://en.wikipedia.org/wiki/Category:Neighborhoods_in_Queens,_New_York").text

# parse data from the html into a beautifulsoup object
soup = BeautifulSoup(data, 'html.parser')

# create a list to store neighborhood data
neighborhoodList = []

# append the data into the list
for row in soup.find_all("div", class_="mw-category")[0].findAll("li"):
    neighborhoodList.append(row.text)

# create a new DataFrame from the list
qn = pd.DataFrame({"Neighborhood": neighborhoodList})

In [15]:
qn['Neighborhood'] = qn['Neighborhood'].astype(str).str[1:]

sep = '('
qn['Neighborhood'] = qn['Neighborhood'].apply(lambda x: x.split(sep,1)[0])
qn['Neighborhood'] = qn['Neighborhood'].str.strip()

In [16]:
# define a function to get coordinates
def get_latlng(neighborhood):
    # initialize your variable to None
    lat_lng_coords = None
    # loop until you get the coordinates
    while(lat_lng_coords is None):
        g = geocoder.arcgis('{}, Brooklyn, New York'.format(neighborhood))
        lat_lng_coords = g.latlng
    return lat_lng_coords

# call the function to get the coordinates, store in a new list using list comprehension
coords = [ get_latlng(neighborhood) for neighborhood in qn["Neighborhood"].tolist() ]

# create temporary dataframe to populate the coordinates into Latitude and Longitude
df_coords = pd.DataFrame(coords, columns=['Latitude', 'Longitude'])

# merge the coordinates into the original dataframe
qn['Latitude'] = df_coords['Latitude']
qn['Longitude'] = df_coords['Longitude']

In [17]:
# save the DataFrame as CSV file
qn.to_csv("qn_neighborhoods.csv", index=False)


# check the neighborhoods and the coordinates
print(qn.shape)
qn

(29, 3)

                                     Neighborhood   Latitude  Longitude
0                                Astoria, Queens‎  40.772050 -73.926060
1                                Bayside, Queens‎  40.777310 -73.780680
2                                 Corona, Queens‎  40.746370 -73.854830
3                 Douglaston–Little Neck, Queens‎  40.768561 -73.747657
4                          East Elmhurst, Queens‎  40.764390 -73.874020
5                               Elmhurst, Queens‎  40.743610 -73.884330
6                          Floral Park, New York‎  40.664506 -73.979842
7                               Flushing, Queens‎  40.706477 -73.925219
8                           Forest Hills, Queens‎  40.722660 -73.847910
9                          Fresh Meadows, Queens‎  40.741620 -73.782990
10                             Glen Oaks, Queens‎  40.748000 -73.713240
11                              Glendale, Queens‎  40.701410 -73.887200
12                          Howard Beach, Queens‎  40.654830 -73.846020
13                       Jackson Heights, Queens‎  40.749400 -73.887560
14                               Jamaica, Queens‎  40.687666 -73.877538
15                     Kew Gardens Hills, Queens‎  40.730020 -73.823400
16                           Kew Gardens, Queens‎  40.708650 -73.828910
17                              Long Island City‎  40.750720 -73.941030
18                               Maspeth, Queens‎  40.727290 -73.895440
19                        Middle Village, Queens‎  40.712380 -73.882700
20             Neighborhoods in Rockaway, Queens‎  40.658961 -73.908310
21                            Ozone Park, Queens‎  40.680120 -73.847360
22  People from Queens, New York by neighborhood‎  40.714000 -73.829990
23                         Richmond Hill, Queens‎  40.700540 -73.828060
24                             Ridgewood, Queens‎  40.698129 -73.910641
25                              Rockaway, Queens‎  40.685531 -73.863764
26                            Whitestone, Queens‎  40.788630 -73.813730
27                             Woodhaven, Queens‎  40.692630 -73.861020
28                              Woodside, Queens‎  40.746960 -73.902790

## Staten Island

In [22]:
# send the GET request
data = requests.get("https://en.wikipedia.org/wiki/Category:Neighborhoods_in_Staten_Island").text

# parse data from the html into a beautifulsoup object
soup = BeautifulSoup(data, 'html.parser')

# create a list to store neighborhood data
neighborhoodList = []

# append the data into the list
for row in soup.find_all("div", class_="mw-category")[0].findAll("li"):
    neighborhoodList.append(row.text)

# create a new DataFrame from the list
si = pd.DataFrame({"Neighborhood": neighborhoodList})

In [19]:
si['Neighborhood'] = si['Neighborhood'].astype(str).str[1:]

sep = '('
si['Neighborhood'] = si['Neighborhood'].apply(lambda x: x.split(sep,1)[0])
si['Neighborhood'] = si['Neighborhood'].str.strip()

In [23]:
si

                           Neighborhood
0   List of Staten Island neighborhoods
1               Annadale, Staten Island
2          Arden Heights, Staten Island
3              Arlington, Staten Island
4               Arrochar, Staten Island
..                                  ...
69     West New Brighton, Staten Island
70            West Shore, Staten Island
71           Westerleigh, Staten Island
72           Willowbrook, Staten Island
73               Woodrow, Staten Island

[74 rows x 1 columns]

In [20]:
# define a function to get coordinates
def get_latlng(neighborhood):
    # initialize your variable to None
    lat_lng_coords = None
    # loop until you get the coordinates
    while(lat_lng_coords is None):
        g = geocoder.arcgis('{}, Brooklyn, New York'.format(neighborhood))
        lat_lng_coords = g.latlng
    return lat_lng_coords

# call the function to get the coordinates, store in a new list using list comprehension
coords = [ get_latlng(neighborhood) for neighborhood in si["Neighborhood"].tolist() ]

# create temporary dataframe to populate the coordinates into Latitude and Longitude
df_coords = pd.DataFrame(coords, columns=['Latitude', 'Longitude'])

# merge the coordinates into the original dataframe
si['Latitude'] = df_coords['Latitude']
si['Longitude'] = df_coords['Longitude']

In [21]:
# save the DataFrame as CSV file
si.to_csv("si_neighborhoods.csv", index=False)


# check the neighborhoods and the coordinates
print(si.shape)
si

(74, 3)

                          Neighborhood   Latitude  Longitude
0   ist of Staten Island neighborhoods  40.642420 -74.075270
1               nnadale, Staten Island  40.690475 -73.992467
2          rden Heights, Staten Island  40.554140 -74.173910
3              rlington, Staten Island  40.690475 -73.992467
4               rrochar, Staten Island  40.690475 -73.992467
..                                 ...        ...        ...
69     est New Brighton, Staten Island  40.642070 -74.093360
70            est Shore, Staten Island  40.690475 -73.992467
71           esterleigh, Staten Island  40.621020 -74.132050
72           illowbrook, Staten Island  40.603170 -74.139050
73               oodrow, Staten Island  40.690475 -73.992467

[74 rows x 3 columns]

In [ ]:
# get the coordinates of New York City
address = 'Bronx, New York'

geolocator = Nominatim(user_agent="coursera-capstone-project")
location = geolocator.geocode(address)
latitude = location.latitude
longitude = location.longitude
print('The geograpical coordinate of Bronx, New York {}, {}.'.format(latitude, longitude))

In [ ]:
# create map of Toronto using latitude and longitude values
map_ny = folium.Map(location=[latitude, longitude], zoom_start=11)

# add markers to map
for lat, lng, neighborhood in zip(bx['Latitude'], bx['Longitude'], bx['Neighborhood']):
    label = '{}'.format(neighborhood)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='#3186cc',
        fill_opacity=0.7).add_to(map_ny)  
    
map_ny